### ISSUE TITLE
Using and configuring cache in NewStormpathMiddleware

### ISSUE THREAD

**Issue by aellerton** [jarias/stormpath-sdk-go#56]
Hi there,

Nice work with this library :)

I'm running the ``/web/example`` and am struggling to see how to set up a cache.

Firstly, to see all the requests being sent I modified ``stormpath.go``, specifically ``Client newRequest()`` adding:

    fmt.Printf("%s %s\n", method, urlStr)

There's a load of requests, many of them identical - that's ok, because I can use a cache to catch the quickly repeated ones... but how?

The ``Client`` cache appears to be set up via ``StormPath.Init`` in the ``NewStormpathMiddleware`` function in ``web.go``:

    stormpath.Init(clientConfig, nil) // me: note the "nil" for cache param

This becomes:

```
func Init(clientConfiguration ClientConfiguration, cache Cache) {
	InitLog()

	tr := &http.Transport{
		TLSClientConfig:    &tls.Config{},
		DisableCompression: true,
	}
	httpClient := &http.Client{Transport: tr}
	httpClient.CheckRedirect = checkRedirect

	client = &Client{clientConfiguration, httpClient, nil, ""}

	if clientConfiguration.CacheManagerEnabled && cache == nil {
		client.Cache = NewLocalCache(clientConfiguration.CacheTTL, clientConfiguration.CacheTTI)
	} else if clientConfiguration.CacheManagerEnabled && cache != nil {
		client.Cache = cache
	}
}
```

My config (i.e. same directory, file named ``stormpath.yaml``) has the cache enabled, so I *think* I'll automatically be getting a local (i.e. memory) cache:

```
    cacheManager:
      enabled: true
      defaultTtl: 300
      defaultTti: 300
      caches:
        # Resource cache configurations, as needed.
        # These are used to override the default TTL/TTI settings
        # for a particular resource type.
        account:
          ttl: 300
          tti: 300
```

But ...

1. There's no way that I can see to tell the system through configuration or code that I want to use a specific cache implementation

2. There's a comment in git that redis cache used to be implemented but was replaced by ledis... but I can't find any of that code.

3. I'm not sure (judging by my printf of http requests) that the cache is being used. I'll debug with the LocalCache and see.

How do you recommend setting up a redis cache for accounts and applications?

Thanks!
A

**Comment by jarias** [comment]
@aellerton 

Once you initialize the middleware you can change the cache impl:

```go
strompath.web.NewStormpathMiddleware(yourNextHandler, yourPublicPaths)
stormpath.GetClient().Cache = yourCacheImpl
```

I think the `NewStormpathMiddleware` func should probable take the cache too, I will probably add that in the next release.

If you don't set a cache and the configuration says the cache is enabled the LocalCache would be used see https://github.com/jarias/stormpath-sdk-go/blob/master/stormpath.go#L56

To create a Redis cache you need to implement the Cache interface https://github.com/jarias/stormpath-sdk-go/blob/master/cache.go#L9

To actually debug the usage of the cache this is the right place to look https://github.com/jarias/stormpath-sdk-go/blob/master/stormpath.go#L204

Hope this helps, let me know if you have more questions.

**Comment by jarias** [comment]
also 

FYI

```
caches:
        # Resource cache configurations, as needed.
        # These are used to override the default TTL/TTI settings
        # for a particular resource type.
        account:
          ttl: 300
          tti: 300
```
This part of the configuration is not implemented in the LocalCache all entities would be cache in a single memory map.
